# Generated by Django 4.2.6 on 2024-01-11 04:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classDate', models.DateTimeField(default=datetime.datetime.now)),
                ('attendanceSubjectCode', models.CharField(default='Not provided', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackTitle', models.CharField(max_length=255)),
                ('feedbackDescription', models.CharField(max_length=2550)),
                ('feedbackAttachment', models.ImageField(blank=True, null=True, upload_to='feedbackAttachment')),
                ('userID', models.CharField(default='Not provided', max_length=255, null=True)),
                ('adminID', models.CharField(default='Not provided', max_length=255, null=True)),
                ('reply', models.CharField(default='Not provided', max_length=2550, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intakeCode', models.CharField(max_length=255, unique=True)),
                ('coordinatorID', models.CharField(default='Not provided', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('leaveID', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('userID', models.IntegerField(default='1', null=True)),
                ('leaveTitle', models.CharField(max_length=255)),
                ('leaveDescription', models.CharField(max_length=255, null=True)),
                ('leaveAttachment', models.ImageField(blank=True, null=True, upload_to='leaveAttatchment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('applyDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectCode', models.CharField(max_length=255, unique=True)),
                ('subjectName', models.CharField(default='Not provided', max_length=255)),
                ('lecturerID', models.CharField(default='Not provided', max_length=255)),
                ('intakeCode', models.CharField(default='Not provided', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intakeCode', models.CharField(default='Not provided', max_length=255)),
                ('phone_number', models.CharField(default='Not provided', max_length=15)),
                ('image', models.ImageField(blank=True, default='faceImage/default.png', null=True, upload_to='faceImage')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
