# Generated by Django 4.2.6 on 2024-02-05 06:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceMonitoringTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absenceLimitName', models.CharField(default='Not provided', max_length=255)),
                ('absenceLimitDays', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('adminId', models.CharField(default='Not provided', max_length=50, primary_key=True, serialize=False)),
                ('adminProfileImage', models.ImageField(blank=True, default='adminProfileImage/default.png', null=True, upload_to='adminProfileImage')),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeTable',
            fields=[
                ('intakeCode', models.CharField(default='Not provided', max_length=255, primary_key=True, serialize=False)),
                ('adminId', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(default='Not provided', max_length=255)),
                ('notifyDate', models.DateTimeField(default=datetime.datetime.now)),
                ('notifyMessage', models.CharField(default='Not provided', max_length=255)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('noted', 'Noted')], default='delivered', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('userId', models.CharField(default='Not provided', max_length=50, primary_key=True, serialize=False)),
                ('faceImageUrl', models.ImageField(blank=True, default='faceImage/default.png', null=True, upload_to='faceImage')),
                ('absenceMonitoringId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.absencemonitoringtable')),
                ('intakeCode', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.intaketable')),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': 'user'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('subjectCode', models.CharField(default='Not provided', max_length=50, primary_key=True, serialize=False)),
                ('subjectName', models.CharField(default='Not provided', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=10)),
                ('noOfUser', models.IntegerField(blank=True, null=True)),
                ('adminTables', models.ManyToManyField(blank=True, related_name='admin', to='system.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(choices=[('User Experience', 'user experience'), ('Attendance', 'attendance'), ('Others', 'others')], default='Attendance', max_length=50)),
                ('reportMessage', models.CharField(default='Not provided', max_length=255)),
                ('creator', models.CharField(default='Not provided', max_length=255)),
                ('reportDate', models.DateTimeField(default=datetime.datetime.now)),
                ('replyMessage', models.CharField(blank=True, default='Not provided', max_length=255, null=True)),
                ('replyDate', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('read', 'Read'), ('replied', 'Replied')], default='delivered', max_length=10)),
                ('receiver', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.adminprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('lecturerId', models.CharField(default='Not provided', max_length=50, primary_key=True, serialize=False)),
                ('lecturerProfileImage', models.ImageField(blank=True, default='lecturerProfileImage/default.png', null=True, upload_to='lecturerProfileImage')),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveTitle', models.CharField(default='Not provided', max_length=255)),
                ('leaveDescription', models.CharField(max_length=255, null=True)),
                ('leaveAttachment', models.ImageField(blank=True, null=True, upload_to='leaveAttatchment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('applyDate', models.DateField(default=datetime.date.today)),
                ('adminID', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.adminprofile')),
                ('userID', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('classCode', models.CharField(default='Not provided', max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=10)),
                ('noOfUser', models.IntegerField(blank=True, null=True)),
                ('intakeTables', models.ManyToManyField(blank=True, related_name='subjects', to='system.intaketable')),
                ('lecturerId', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.lecturerprofile')),
                ('subjectCode', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.subjecttable')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='Not provided', max_length=255)),
                ('noAttendedUser', models.IntegerField(default=0)),
                ('totalUser', models.IntegerField(default=0)),
                ('classDate', models.DateTimeField(default=datetime.datetime.now)),
                ('method', models.CharField(choices=[('manual', 'Manual'), {'Face Recognition', 'face recognition'}], default='manual', max_length=20)),
                ('attendedUser', models.ManyToManyField(blank=True, related_name='attendance_tables', to='system.userprofile')),
                ('classCode', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.classtable')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('absent', 'Absent'), ('attended', 'Attended'), ('mc', 'MC'), ('excuse', 'Excuse'), ('Emergency', 'Emergency'), ('curriculum', 'Curriculum'), ('late', 'Late')], default='absent', max_length=10)),
                ('checkIn', models.DateTimeField(default=datetime.datetime.now)),
                ('relation_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.attendancetable')),
                ('userId', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='absencemonitoringtable',
            name='adminID',
            field=models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.adminprofile'),
        ),
    ]
