# Generated by Django 4.2.6 on 2024-01-23 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtable',
            name='receiver',
        ),
    ]
