# Generated by Django 4.2.6 on 2023-10-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendanceSubjectCode',
            field=models.CharField(default='Not provided', max_length=255, null=True),
        ),
    ]
