# Generated by Django 4.2.6 on 2023-10-29 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classDate',
            field=models.DateTimeField(default=datetime.date.today, verbose_name=datetime.date.today),
            preserve_default=False,
        ),
    ]
