# Generated by Django 4.2.6 on 2023-10-29 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_attendance_classdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classDate',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
