# Generated by Django 4.2.6 on 2023-10-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_attendance_attendancesubjectcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leaveAttachment',
            field=models.ImageField(blank=True, null=True, upload_to='leaveAttatchment'),
        ),
    ]
