# Generated by Django 4.2.6 on 2024-01-23 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_notificationtable_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='receiverAdmin',
            field=models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.adminprofile'),
        ),
        migrations.CreateModel(
            name='NotificationTableUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifyUserDate', models.DateTimeField(default=datetime.datetime.now)),
                ('notifyUserMessage', models.CharField(default='Not provided', max_length=255)),
                ('statusUser', models.CharField(choices=[('delivered', 'Delivered'), ('noted', 'Noted')], default='delivered', max_length=10)),
                ('receiverUser', models.ForeignKey(default='Not provided', on_delete=django.db.models.deletion.CASCADE, to='system.userprofile')),
            ],
        ),
    ]
