# Generated by Django 4.2.6 on 2024-01-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_notificationtable_receiveradmin_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationTableUser',
            new_name='NotificationUser',
        ),
    ]
