# Generated by Django 4.2.6 on 2024-02-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_attendancestatus_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetable',
            name='nameList',
            field=models.ManyToManyField(blank=True, related_name='name_list_tables', to='system.userprofile'),
        ),
        migrations.AlterField(
            model_name='attendancetable',
            name='attendedUser',
            field=models.ManyToManyField(blank=True, related_name='attended_user_tables', to='system.userprofile'),
        ),
        migrations.AlterField(
            model_name='attendancetable',
            name='method',
            field=models.CharField(choices=[('manual', 'Manual'), ('face recognition', 'Face Recognition')], default='manual', max_length=20),
        ),
    ]
