# Generated by Django 4.2.6 on 2023-10-29 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_attendance_classdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='classDate',
        ),
    ]
