# Generated by Django 4.2.6 on 2024-01-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_rename_notificationtableuser_notificationuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtable',
            name='receiverAdmin',
        ),
        migrations.AddField(
            model_name='notificationtable',
            name='receiver',
            field=models.CharField(default='Not provided', max_length=255),
        ),
        migrations.DeleteModel(
            name='NotificationUser',
        ),
    ]
