# Generated by Django 4.2.9 on 2024-02-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_attendancetable_namelist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faceImage')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='face_images',
            field=models.ManyToManyField(to='system.faceimage'),
        ),
    ]
