# Generated by Django 4.2.9 on 2024-02-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_faceimage_userprofile_face_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttable',
            name='reportAttachment',
            field=models.ImageField(blank=True, null=True, upload_to='reportAttachment'),
        ),
    ]
