# Generated by Django 4.2.6 on 2024-01-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_remove_notificationtable_receiveradmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetable',
            name='attendedUser',
            field=models.ManyToManyField(blank=True, related_name='attendance_tables', to='system.userprofile'),
        ),
    ]
