# Generated by Django 4.2.6 on 2023-10-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_leave_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='userID',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
