# Generated by Django 4.2.6 on 2023-10-30 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_leave_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='applyDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='leave',
            name='endDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='leave',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
