# Generated by Django 4.2.9 on 2024-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_reporttable_reportattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancestatus',
            name='status',
            field=models.CharField(choices=[('absent', 'Absent'), ('attended', 'Attended'), ('mc', 'MC'), ('excuse', 'Excuse'), ('emergency', 'Emergency'), ('curriculum', 'Curriculum'), ('late', 'Late')], default='absent', max_length=10),
        ),
    ]
