# Generated by Django 4.2.9 on 2024-03-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_attendancestatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='face_images',
        ),
        migrations.DeleteModel(
            name='FaceImage',
        ),
    ]
