# Generated by Django 4.2.9 on 2024-03-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_remove_userprofile_face_images_delete_faceimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttable',
            name='reportTitle',
            field=models.CharField(default='Attendance', max_length=50),
        ),
    ]
